// Simple EN/NO language system - no external dependencies

export const getLang = () => {
  try { return localStorage.getItem('hs_lang') || 'en' } catch { return 'en' }
}

export const setLang = (code) => {
  try { localStorage.setItem('hs_lang', code) } catch {}
}

export const NO = {
  // Auth
  login: 'Logg inn', createAccount: 'Opprett konto', email: 'E-post',
  password: 'Passord', yourName: 'Ditt navn', newHere: 'Ny her?',
  haveAccount: 'Har du konto?', loggingIn: 'Logger inn…',
  // Home
  welcome: 'Velkommen tilbake', manageEstates: 'Administrer dine estates eller bli med med en invitasjonskode',
  newEstate: '+ Ny estate', joinEstate: 'Bli med i en estate',
  joinDesc: 'Har du en invitasjonskode? Skriv den inn under.',
  joinPlaceholder: 'Skriv invitasjonskode (f.eks. AB3X9K)',
  join: 'Bli med', noEstates: 'Ingen estates ennå. Opprett en eller bli med med en invitasjonskode.',
  createFirst: 'Opprett første estate', estateName: 'Navn på estate *',
  estateDesc: 'Beskrivelse (valgfri)', createEstate: 'Opprett estate', cancel: 'Avbryt',
  // Estate
  totalItems: 'Gjenstander totalt', myInterests: 'Mine interesser',
  contested: 'Ettertraktede', unwanted: 'Ingen vil ha', assigned: 'Tildelt',
  addItem: '+ Legg til gjenstand', manage: '⚙️ Administrer',
  items: 'Gjenstander', analytics: 'Analyse',
  allCategories: 'Alle kategorier', allItems: 'Alle gjenstander',
  taskChecklist: '📋 Oppgaveliste', taskDesc: 'Steg-for-steg-veiledning',
  docVault: '🔒 Dokumenthvelv', docDesc: 'Testamenter, skjøter, ID',
  heirs: '👨‍👩‍👧 Arvinger og fordeling', heirsDesc: 'Rettferdig fordelingskalkulator',
  goodwill: '⭐ Goodwill og arbeid', goodwillDesc: 'Oppgaver, rettferdighet, karma',
  noItemsYet: 'Ingen gjenstander ennå.', addFirstItem: 'Legg til første gjenstand',
  // Add item
  addItemTitle: 'Legg til gjenstand', addItemSub: 'Ta et bilde — AI identifiserer og verdsetter automatisk',
  photoStep: '📸 Bilde', detailsStep: '📝 Detaljer', valueStep: '💰 Verdi',
  takePhoto: 'Trykk for å ta eller laste opp bilde', aiIdentifies: 'AI identifiserer gjenstanden og estimerer verdi',
  retake: 'Ta nytt bilde', analyzeAI: '🤖 Analyser med AI', analyzing: '🤖 Analyserer…',
  skipAI: 'Hopp over — fyll inn manuelt →',
  itemName: 'Navn på gjenstand *', category: 'Kategori', condition: 'Tilstand',
  description: 'Beskrivelse', back: '← Tilbake', getEstimate: 'Få verdiestimat →',
  saveWithout: '✓ Lagre uten verdiestimat',
  excellent: 'Utmerket', good: 'God', fair: 'Middels', poor: 'Dårlig',
  purchasePrice: 'Kjøpspris (NOK)', yearBought: 'Kjøpsår',
  ownEstimate: 'Ditt eget estimat (valgfri)', addItemBtn: '✓ Legg til gjenstand',
  saving: 'Lagrer…', estimating: '🔍 Estimerer markedsverdi…',
  aiMarketEst: 'AI Markedsestimat', low: 'Lav', high: 'Høy', likelyVal: 'Mest sannsynlig',
  marketRefs: 'Markedsreferanser', insuranceModel: 'Forsikringens avskrivningsmodell',
  verifyYourself: 'Sjekk selv', finnLink: '🇳🇴 Finn.no →', ebayLink: '🌍 eBay solgt →',
  disclaimer: '⚠️ Estimater er kun veiledende — ikke profesjonell takst.',
  knowPurchasePrice: 'Vet du kjøpsprisen? Legger avskrivning til estimatet.',
  finalValue: 'Endelig verdi (redigerbar)', autoFilled: 'AI fylte dette inn — du kan endre det',
  // Item detail
  registerInterest: 'Registrer interesse', withdrawInterest: '✓ Du er interessert — klikk for å trekke tilbake',
  whyWant: 'Hvorfor vil du ha denne gjenstanden?', whyOptional: '(valgfri — synlig for alle)',
  whyPlaceholder: 'f.eks. Jeg husker denne fra barndommen…', registerBtn: 'Registrer interesse',
  interestedCount: 'Interesserte', noInterest: 'Ingen har vist interesse ennå.',
  whoGets: 'Hvem får denne gjenstanden?', assignItem: '✅ Tildel gjenstand',
  assignedTo: 'Tildelt til', officiallyDist: 'Denne gjenstanden er offisielt fordelt ✅',
  deleteItem: 'Slett gjenstand…', cannotUndo: 'Kan ikke angres.', delete: 'Slett',
  comments: 'Kommentarer', noComments: 'Ingen kommentarer ennå. Vær den første til å dele et minne!',
  commentPlaceholder: 'Del en kommentar eller minne… (Enter for å sende)',
  send: 'Send', commentsUpgrade: 'Kommentarer krever betalt plan — la familien dele minner!',
  // Feedback
  shareFeedback: 'Del tilbakemelding', bug: '🐛 Feil', idea: '💡 Idé', general: '💬 Generelt',
  bugPlaceholder: 'Hva gikk galt? Hva forventet du?',
  ideaPlaceholder: 'Hvilken funksjon ville gjort dette mer nyttig?',
  generalPlaceholder: 'Fortell oss hva du synes…',
  npsQuestion: 'Hvor sannsynlig er det at du vil anbefale HeirSplit? (valgfri)',
  notLikely: 'Lite sannsynlig', veryLikely: 'Svært sannsynlig',
  sendFeedback: 'Send tilbakemelding', sending: 'Sender…',
  thankYou: 'Takk!', feedbackHelps: 'Din tilbakemelding hjelper oss å bli bedre',
  // Nav
  upgrade: 'Oppgrader', myProfile: '⚙️ Min profil', founderDash: '🔭 Founder dashboard', logout: '🚪 Logg ut',
}

export const EN = {
  login: 'Log in', createAccount: 'Create account', email: 'Email',
  password: 'Password', yourName: 'Your name', newHere: 'New here?',
  haveAccount: 'Have an account?', loggingIn: 'Logging in…',
  welcome: 'Welcome back', manageEstates: 'Manage your estates or join one with an invite code',
  newEstate: '+ New estate', joinEstate: 'Join an estate',
  joinDesc: 'Got an invite code? Enter it below to join the family.',
  joinPlaceholder: 'Enter invite code (e.g. AB3X9K)',
  join: 'Join', noEstates: 'No estates yet. Create one or join with an invite code.',
  createFirst: 'Create first estate', estateName: 'Estate name *',
  estateDesc: 'Description (optional)', createEstate: 'Create estate', cancel: 'Cancel',
  totalItems: 'Total items', myInterests: 'My interests',
  contested: 'Contested', unwanted: 'Unwanted', assigned: 'Assigned',
  addItem: '+ Add item', manage: '⚙️ Manage',
  items: 'Items', analytics: 'Analytics',
  allCategories: 'All categories', allItems: 'All items',
  taskChecklist: '📋 Task checklist', taskDesc: 'Step-by-step guide',
  docVault: '🔒 Document vault', docDesc: 'Wills, deeds, IDs',
  heirs: '👨‍👩‍👧 Heirs & distribution', heirsDesc: 'Fair split calculator',
  goodwill: '⭐ Goodwill & work', goodwillDesc: 'Tasks, fairness, karma',
  noItemsYet: 'No items yet.', addFirstItem: 'Add first item',
  addItemTitle: 'Add item', addItemSub: 'Take a photo — AI identifies and values automatically',
  photoStep: '📸 Photo', detailsStep: '📝 Details', valueStep: '💰 Value',
  takePhoto: 'Tap to take or upload photo', aiIdentifies: 'AI identifies item and estimates value',
  retake: 'Retake', analyzeAI: '🤖 Analyze with AI', analyzing: '🤖 Analyzing…',
  skipAI: 'Skip — fill in manually →',
  itemName: 'Item name *', category: 'Category', condition: 'Condition',
  description: 'Description', back: '← Back', getEstimate: 'Get value estimate →',
  saveWithout: '✓ Save without value estimate',
  excellent: 'Excellent', good: 'Good', fair: 'Fair', poor: 'Poor',
  purchasePrice: 'Purchase price (NOK)', yearBought: 'Year bought',
  ownEstimate: 'Your own estimate (optional)', addItemBtn: '✓ Add item',
  saving: 'Saving…', estimating: '🔍 Estimating market value…',
  aiMarketEst: 'AI Market Estimate', low: 'Low', high: 'High', likelyVal: 'Most likely',
  marketRefs: 'Market references', insuranceModel: 'Insurance depreciation model',
  verifyYourself: 'Verify yourself', finnLink: '🌍 eBay sold →', ebayLink: '🌍 eBay sold →',
  disclaimer: '⚠️ Estimates are for guidance only — not professional appraisal.',
  knowPurchasePrice: 'Know the purchase price? Adds depreciation to the estimate.',
  finalValue: 'Final value (editable)', autoFilled: 'AI filled this in — you can edit it',
  registerInterest: 'Register interest', withdrawInterest: '✓ You\'re interested — click to withdraw',
  whyWant: 'Why do you want this item?', whyOptional: '(optional — visible to all)',
  whyPlaceholder: 'e.g. I remember this from childhood…', registerBtn: 'Register interest',
  interestedCount: 'Interested', noInterest: 'No one has shown interest yet.',
  whoGets: 'Who gets this item?', assignItem: '✅ Assign item',
  assignedTo: 'Assigned to', officiallyDist: 'This item has been officially distributed ✅',
  deleteItem: 'Delete item…', cannotUndo: 'Cannot be undone.', delete: 'Delete',
  comments: 'Comments', noComments: 'No comments yet. Be the first to share a memory!',
  commentPlaceholder: 'Share a memory or comment… (Enter to send)',
  send: 'Send', commentsUpgrade: 'Comments require a paid plan — let the family share memories!',
  shareFeedback: 'Share feedback', bug: '🐛 Bug', idea: '💡 Idea', general: '💬 General',
  bugPlaceholder: 'What went wrong? What did you expect?',
  ideaPlaceholder: 'What feature would make this more useful?',
  generalPlaceholder: 'Tell us what you think…',
  npsQuestion: 'How likely are you to recommend HeirSplit? (optional)',
  notLikely: 'Not likely', veryLikely: 'Very likely',
  sendFeedback: 'Send feedback', sending: 'Sending…',
  thankYou: 'Thank you!', feedbackHelps: 'Your feedback helps us improve',
  upgrade: 'Upgrade', myProfile: '⚙️ My profile', founderDash: '🔭 Founder dashboard', logout: '🚪 Log out',
}

export const useT = () => getLang() === 'no' ? NO : EN
export const t = (key) => (getLang() === 'no' ? NO : EN)[key] || key
